import { Edit3, Plus, Trash2, X } from 'lucide-react';
import { useEffect, useState } from 'react';
import LoadingState, { EmptyState, ErrorState } from '../../components/common/States';
import useFetch from '../../hooks/useFetch';
import { api } from '../../services/api';
import { SLUG_PATTERN, slugify } from '../../utils/formatters';

export default function TaxonomyPage({ type }) {
  const singular = type === 'categories' ? 'categoría' : 'tecnología';
  const { data, loading, error, refetch } = useFetch(() => api.get(`/admin/${type}`), [type]);
  const items = data?.[type] || [];
  const [editing, setEditing] = useState(null);
  const [form, setForm] = useState({ name: '', slug: '', icon: '', active: true, order: 0 });
  const [actionError, setActionError] = useState('');
  useEffect(() => { setEditing(null); setForm({ name: '', slug: '', icon: '', active: true, order: 0 }); }, [type]);
  const submit = async (event) => { event.preventDefault(); setActionError(''); const payload = { ...form, order: Number(form.order) }; try { if (editing) await api.put(`/admin/${type}/${editing}`, payload); else await api.post(`/admin/${type}`, payload); setEditing(null); setForm({ name: '', slug: '', icon: '', active: true, order: 0 }); await refetch(); } catch (currentError) { setActionError(currentError.message); } };
  const edit = (item) => { setEditing(item._id); setForm({ name: item.name, slug: item.slug, icon: item.icon || '', active: item.active, order: item.order || 0 }); };
  const remove = async (item) => { if (!window.confirm(`¿Eliminar ${singular} “${item.name}”?`)) return; setActionError(''); try { await api.delete(`/admin/${type}/${item._id}`); await refetch(); } catch (currentError) { setActionError(currentError.message); } };
  return <div className="admin-page"><div className="admin-heading"><div><span className="eyebrow">Taxonomías</span><h1>{type === 'categories' ? 'Categorías' : 'Tecnologías'}</h1><p>Opciones reutilizables para clasificar proyectos.</p></div></div>{actionError && <p className="form-status form-status--error" role="alert">{actionError}</p>}<div className="taxonomy-layout"><form className="admin-form compact-form" onSubmit={submit}><section><h2>{editing ? `Editar ${singular}` : `Nueva ${singular}`}</h2><label>Nombre<input value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value, slug: editing ? form.slug : slugify(event.target.value) })} required /></label><label>Slug<input value={form.slug} onChange={(event) => setForm({ ...form, slug: event.target.value })} pattern={SLUG_PATTERN} title="Usá solo minúsculas, números y guiones" required /></label>{type === 'technologies' && <label>Icono o URL<input value={form.icon} onChange={(event) => setForm({ ...form, icon: event.target.value })} /></label>}<label>Orden<input type="number" value={form.order} onChange={(event) => setForm({ ...form, order: event.target.value })} /></label><label className="check-label"><input type="checkbox" checked={form.active} onChange={(event) => setForm({ ...form, active: event.target.checked })} />Activo</label><button className="button button--primary"><Plus />{editing ? 'Guardar cambios' : 'Crear'}</button>{editing && <button className="button button--secondary" type="button" onClick={() => setEditing(null)}><X />Cancelar</button>}</section></form><div>{loading && <LoadingState />}{error && <ErrorState message={error} onRetry={refetch} />}{!loading && !error && items.length === 0 && <EmptyState />}{items.length > 0 && <div className="admin-table-wrap"><table className="admin-table admin-table--taxonomy"><thead><tr><th>Nombre</th><th>Estado</th><th>Orden</th><th><span className="sr-only">Acciones</span></th></tr></thead><tbody>{items.map((item) => <tr key={item._id}><td><strong>{item.name}</strong><small>/{item.slug}</small></td><td>{item.active ? 'Activo' : 'Inactivo'}</td><td>{item.order || 0}</td><td><div className="row-actions"><button className="icon-action" onClick={() => edit(item)} aria-label={`Editar ${item.name}`}><Edit3 /></button><button className="icon-action icon-action--danger" onClick={() => remove(item)} aria-label={`Eliminar ${item.name}`}><Trash2 /></button></div></td></tr>)}</tbody></table></div>}</div></div></div>;
}
